# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

##############################################################
# 入力補助用のサンプル コピペして、不要な行を削除、編集して使う
##############################################################
# Shelf.create(room: "9F", position: "4-1-L", genre: "携帯アプリ")
# Shelf.create(room: "9F", position: "4-1-R", genre: "機器制御")
# Shelf.create(room: "9F", position: "4-2-L", genre: "組み込み")
# Shelf.create(room: "9F", position: "4-2-R", genre: "PC組み立て")
# Shelf.create(room: "9F", position: "4-3-L", genre: "GUI")
# Shelf.create(room: "9F", position: "4-3-R", genre: "WEBユーザビリティ")
# Shelf.create(room: "9F", position: "4-4-L", genre: "TeX")
# Shelf.create(room: "9F", position: "4-4-R", genre: "Emacs")
# Shelf.create(room: "9F", position: "4-5-L", genre: "Flash")
# Shelf.create(room: "9F", position: "4-5-R", genre: "Adobeソフト")
# Shelf.create(room: "9F", position: "4-6-L", genre: "画像ソフト")
# Shelf.create(room: "9F", position: "4-6-R", genre: "動画ソフト")
# Shelf.create(room: "9F", position: "4-7-L", genre: "Officeソフト")
# Shelf.create(room: "9F", position: "4-7-R", genre: "計算ソフト")
# Shelf.create(room: "9F", position: "4-8-L", genre: "Windows")
# Shelf.create(room: "9F", position: "4-8-R", genre: "Windows")
# Shelf.create(room: "9F", position: "4-9-L", genre: "Windows")
# Shelf.create(room: "9F", position: "4-9-R", genre: "Windows")
####
Shelf.create(room: "9F", position: "1-2-L", genre: "携帯アプリ")
Shelf.create(room: "9F", position: "1-2-R", genre: "機器制御")
Shelf.create(room: "9F", position: "1-3-L", genre: "組み込み")
Shelf.create(room: "9F", position: "1-3-R", genre: "PC組み立て")
Shelf.create(room: "9F", position: "1-4-L", genre: "GUI")
Shelf.create(room: "9F", position: "1-4-R", genre: "WEBユーザビリティ")
Shelf.create(room: "9F", position: "1-5-L", genre: "TeX")
Shelf.create(room: "9F", position: "1-5-R", genre: "Emacs")
Shelf.create(room: "9F", position: "1-6-L", genre: "Flash")
Shelf.create(room: "9F", position: "1-6-R", genre: "Adobeソフト")
Shelf.create(room: "9F", position: "1-7-L", genre: "画像ソフト")
Shelf.create(room: "9F", position: "1-7-R", genre: "動画ソフト")
Shelf.create(room: "9F", position: "1-8-L", genre: "Officeソフト")
Shelf.create(room: "9F", position: "1-8-R", genre: "計算ソフト")
Shelf.create(room: "9F", position: "1-9-L", genre: "Windows")

Shelf.create(room: "9F", position: "2-1-L", genre: "UNIX管理")
Shelf.create(room: "9F", position: "2-1-R", genre: "Xwindow")
Shelf.create(room: "9F", position: "2-2-L", genre: "UNIX配布形態")
Shelf.create(room: "9F", position: "2-2-R", genre: "バーチャルOS")
Shelf.create(room: "9F", position: "2-3-L", genre: "Linuxコマンド")
Shelf.create(room: "9F", position: "2-4-L", genre: "ネットワーク")
Shelf.create(room: "9F", position: "2-4-R", genre: "サーバ管理")
Shelf.create(room: "9F", position: "2-5-L", genre: "バージョン管理")
Shelf.create(room: "9F", position: "2-5-R", genre: "テスト手法")
Shelf.create(room: "9F", position: "2-6-L", genre: "UML")
Shelf.create(room: "9F", position: "2-7-L", genre: "オブジェクト指向")
Shelf.create(room: "9F", position: "2-7-R", genre: "デザインパターン")
Shelf.create(room: "9F", position: "2-8-L", genre: "コンパイラ")
Shelf.create(room: "9F", position: "2-9-L", genre: "WSH")

Shelf.create(room: "9F", position: "3-1-L", genre: "XML")
Shelf.create(room: "9F", position: "3-2-L", genre: "DB")
Shelf.create(room: "9F", position: "3-2-R", genre: "NoSQL")
Shelf.create(room: "9F", position: "3-3-L", genre: "SQL")
Shelf.create(room: "9F", position: "3-4-L", genre: "Webサーバ")
Shelf.create(room: "9F", position: "3-4-R", genre: "Web技術")
Shelf.create(room: "9F", position: "3-5-L", genre: "WebAPI")
Shelf.create(room: "9F", position: "3-5-R", genre: "クラウド")
Shelf.create(room: "9F", position: "3-6-L", genre: "Google技術")
Shelf.create(room: "9F", position: "3-7-L", genre: "SNS")
Shelf.create(room: "9F", position: "3-8-L", genre: "OS")
Shelf.create(room: "9F", position: "3-9-L", genre: "IT一般")

Shelf.create(room: "9F", position: "4-1-L", genre: "関数型言語")
Shelf.create(room: "9F", position: "4-1-R", genre: "手続型言語")
Shelf.create(room: "9F", position: "4-2-L", genre: "C#")
Shelf.create(room: "9F", position: "4-3-L", genre: "PHP")
Shelf.create(room: "9F", position: "4-3-R", genre: "PHPプレームワーク")
Shelf.create(room: "9F", position: "4-4-L", genre: "Ruby 初級")
Shelf.create(room: "9F", position: "4-4-R", genre: "Ruby 中級")
Shelf.create(room: "9F", position: "4-5-L", genre: "Ruby Rails")
Shelf.create(room: "9F", position: "4-5-R", genre: "Ruby 上級")
Shelf.create(room: "9F", position: "4-6-L", genre: "Javascript")
Shelf.create(room: "9F", position: "4-6-R", genre: "WSH")
Shelf.create(room: "9F", position: "4-7-L", genre: "Ajax")
Shelf.create(room: "9F", position: "4-7-R", genre: "HTML")
Shelf.create(room: "9F", position: "4-8-L", genre: "スクリプト言語")
Shelf.create(room: "9F", position: "4-8-R", genre: "プログラム言語一覧")

Shelf.create(room: "9F", position: "5-1-L", genre: "C++")
Shelf.create(room: "9F", position: "5-1-R", genre: "Windowsプログラミング")
Shelf.create(room: "9F", position: "5-2-L", genre: "C基礎")
Shelf.create(room: "9F", position: "5-3-L", genre: "C応用")
Shelf.create(room: "9F", position: "5-3-R", genre: "プログラミングコンテスト")
Shelf.create(room: "9F", position: "5-4-L", genre: "Cアルゴリズム")
Shelf.create(room: "9F", position: "5-5-L", genre: "Java初級")
Shelf.create(room: "9F", position: "5-6-L", genre: "Javaフレームワーク")
Shelf.create(room: "9F", position: "5-6-R", genre: "Javaアルゴリズム")
Shelf.create(room: "9F", position: "5-7-L", genre: "Javaグラフィックス")
Shelf.create(room: "9F", position: "5-8-L", genre: "Javaネットワーク")
Shelf.create(room: "9F", position: "5-8-R", genre: "JavaJSP")
Shelf.create(room: "9F", position: "5-9-L", genre: "科学技術一般")

Shelf.create(room: "9F", position: "6-1-L", genre: "ゲームプログラミング 全般")
Shelf.create(room: "9F", position: "6-2-L", genre: "ゲームプログラミング CG")
Shelf.create(room: "9F", position: "6-3-L", genre: "ゲームプログラミング 各論")
Shelf.create(room: "9F", position: "6-4-L", genre: "ゲームプログラミング Java")
Shelf.create(room: "9F", position: "6-5-L", genre: "ゲームプログラミング AI")
Shelf.create(room: "9F", position: "6-5-R", genre: "ゲームプログラミング ボード")
Shelf.create(room: "9F", position: "6-6-L", genre: "情報数学")
Shelf.create(room: "9F", position: "6-6-R", genre: "情報理論")
Shelf.create(room: "9F", position: "6-7-L", genre: "知識工学")
Shelf.create(room: "9F", position: "6-7-R", genre: "確率統計")
Shelf.create(room: "9F", position: "6-8-L", genre: "教養数学")
Shelf.create(room: "9F", position: "6-9-L", genre: "教養物理")
Shelf.create(room: "9F", position: "6-9-R", genre: "電気電子")

Shelf.create(room: "9F", position: "7-4-L", genre: "LEGOMindstorm和書")
Shelf.create(room: "9F", position: "7-5-L", genre: "LEGOMindstorm洋書NXT")
Shelf.create(room: "9F", position: "7-6-L", genre: "LEGOMindstorm洋書RCX")
Shelf.create(room: "9F", position: "7-7-L", genre: "LEGO一般")
Shelf.create(room: "9F", position: "7-7-R", genre: "ロボット一般")

Shelf.create(room: "9F", position: "10-3-L", genre: "就職試験 数理問題")
Shelf.create(room: "9F", position: "10-3-R", genre: "就職試験 常識問題")
Shelf.create(room: "9F", position: "10-4-L", genre: "就職試験 面接")
Shelf.create(room: "9F", position: "10-4-R", genre: "教育 学校情報")
Shelf.create(room: "9F", position: "10-5-L", genre: "会社情報")
Shelf.create(room: "9F", position: "10-6-L", genre: "情報系読物 SE")
Shelf.create(room: "9F", position: "10-6-R", genre: "情報系読物 ハッカー")
Shelf.create(room: "9F", position: "10-7-L", genre: "マネジメント")
Shelf.create(room: "9F", position: "10-7-R", genre: "経営情報")
Shelf.create(room: "9F", position: "10-8-L", genre: "情報系読物 ゲーム")

Shelf.create(room: "9F", position: "11-3-L", genre: "資格試験 基本情報")
Shelf.create(room: "9F", position: "11-3-R", genre: "その他")
Shelf.create(room: "9F", position: "11-4-L", genre: "応用")
Shelf.create(room: "9F", position: "11-4-R", genre: "上級")
Shelf.create(room: "9F", position: "11-5-L", genre: "技術表現 ライティング")
Shelf.create(room: "9F", position: "11-5-R", genre: "プレゼンテーション")
Shelf.create(room: "9F", position: "11-6-L", genre: "論理思考")
Shelf.create(room: "9F", position: "11-6-R", genre: "仕事術")
Shelf.create(room: "9F", position: "11-7-L", genre: "英語 語彙")
Shelf.create(room: "9F", position: "11-7-R", genre: "英語 試験")
Shelf.create(room: "9F", position: "11-8-L", genre: "論文")
Shelf.create(room: "9F", position: "11-8-R", genre: "発表")
Shelf.create(room: "", position: "未登録", genre: "")
